version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  db:
    container_name: database
    image: mysql:5.7
    # volumes:
    #   - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: db
      MYSQL_ROOT_PORT: 3306
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
    restart: always

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
